/*
STM32G0 Bootloader
Jonah Swain

Application main (header)
Main application code
*/

/* INCLUDE GUARD */
#pragma once
#ifndef APP_MAIN_H
#define APP_MAIN_H

/* TEST PROGRAM */
// Change this to the desired test program name
#define TEST_BLINK

/* DEPENDENCIES */
#include <stdint.h>                 // Fixed width integer data types
#include "stm32g0xx_hal.h"          // STM32G0 hardware abstraction layer
#include "bootloader_common.h"      // Dispatch table for application-accessible bootloader functions
#include "memory_map.h"             // Device memory map

#ifdef TEST_IAP_AS1
#include "as1_blink.h"              // Blink program binary as C header
#endif

#ifdef TEST_IAP_AS2
#include "as2_blink.h"              // Blink program binary as C header
#endif

#ifdef TEST_IAP_AS2_PRIO_AUTO
#include "as2_blink.h"              // Blink program binary as C header
#endif

#ifdef TEST_VT_CHECKSUM_VALID
#include "as2_blink.h"              // Blink program binary as C header
#endif

#ifdef TEST_VT_CHECKSUM_INVALID
#include "as2_blink_bad_checksum.h" // Blink program binary as C header with bad checksum
#endif

#ifdef TEST_APP_CHECKSUM_VALID
#include "as2_blink.h"              // Blink program binary as C header
#endif

#ifdef TEST_APP_CHECKSUM_INVALID
#include "as2_blink_bad_checksum.h" // Blink program binary as C header with bad checksum
#endif

/* CONSTANT DEFINITIONS AND MACROS */
#define BLINK_DELAY 500
#define LD4_Port GPIOA
#define LD4_Pin GPIO_PIN_5

/* TYPE DEFINITIONS AND ENUMERATIONS */


/* GLOBAL VARIABLES */


/* FUNCTIONS */
void main(); // Application main function

void SystemClock_Config(); // Configures the system clock (Auto-generated by STM32CubeIDE)

void Error_Handler(); // Default error handler (required by HAL)

#endif